[general]
dateformat=%F %T

[logfiles]
; Write all verbose/warning/error/debug to a file we can tail
/var/log/asterisk/full => notice,warning,error,verbose,dtmf,fax
console => notice,warning,error,verbose
