; Asterisk Manager Interface (AMI) — for API integration
[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1
displayconnects = no

[amiuser]
secret = AmiPassword!
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.255
read = all
write = all
writetimeout = 5000
